small1: gqp_placer.py ../benchmarks/toy1
	python3 gqp_placer.py ../benchmarks/toy1
	python ../visualization/visualize.py final.txt

small2: gqp_placer.py ../benchmarks/toy2
	python3 gqp_placer.py ../benchmarks/toy2
	python ../visualization/visualize.py final.txt

small3: gqp_placer.py ../benchmarks/fract
	python3 gqp_placer.py ../benchmarks/fract
	python ../visualization/visualize.py final.txt

small4: gqp_placer.py ../benchmarks/primary1
	python3 gqp_placer.py ../benchmarks/primary1
	python ../visualization/visualize.py final.txt

small5: gqp_placer.py ../benchmarks/struct
	python3 gqp_placer.py ../benchmarks/struct
	python ../visualization/visualize.py final.txt

large1: gqp_placer.py ../benchmarks/industry1
	python3 gqp_placer.py ../benchmarks/industry1
	python ../visualization/visualize.py final.txt

large2: gqp_placer.py ../benchmarks/biomed
	python3 gqp_placer.py ../benchmarks/biomed
	python ../visualization/visualize.py final.txt

large3: gqp_placer.py ../benchmarks/industry2
	python3 gqp_placer.py ../benchmarks/industry2
	python ../visualization/visualize.py final.txt

clean:
	rm -f final.txt
